
spring:
  application:
    name: gateway       # file name should ba same as spring application name

  cloud:
    discovery:
      enabled: true
    gateway:
      #      discovery:
      #        location:
      #          enabled: true
      mvc:
        routes:
          - id: student
            uri: http://localhost:8090
            predicates:
              - Path=/api/student/**
          - id: school
            uri: http://localhost:8070
            predicates:
              - Path=/api/school/**

eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

management:
  tracing:
    sampling:
      probability: 1.0
